import{createServer}from'node:http'
import{createHash,randomBytes,randomUUID}from'node:crypto'
import{pathToFileURL}from'node:url'
import{config as loadConfig}from'./config.mjs'
import{RewardRepository,publicClaim}from'./db.mjs'
import{verifyLicenseToken,licenseLabel}from'./license.mjs'
import{ResendEmailProvider}from'./email.mjs'
import{createSession,destroySession,readSession,verifyAdminPassword}from'./auth.mjs'
import{adminHtml,loginHtml}from'./admin-ui.mjs'
const STATUSES=new Set(['PENDING','PREPARING','SHIPPED','DELIVERED','CANCELLED']),mainIds=Array.from({length:12},(_,i)=>`box-${String(i+1).padStart(2,'0')}`)
const hash=v=>createHash('sha256').update(v).digest('hex'),bearer=r=>String(r.headers.authorization||'').replace(/^Bearer\s+/i,''),cookies=r=>Object.fromEntries(String(r.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))
const json=(r,s,status,value,extra={})=>{s.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...extra});s.end(JSON.stringify(value))}
const html=(s,value)=>{s.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'"});s.end(value)}
const body=async r=>{const chunks=[];let size=0;for await(const c of r){size+=c.length;if(size>32768)throw Object.assign(new Error('BODY_TOO_LARGE'),{status:413});chunks.push(c)}return JSON.parse(Buffer.concat(chunks).toString('utf8'))}
const complete=v=>Boolean(v&&v.campaignCompleted===true&&v.progress===100&&v.completionId&&v.completedAt&&Array.isArray(v.solvedIds)&&v.solvedIds.length===12&&mainIds.every(id=>v.solvedIds.includes(id)))
const physical=(l,c)=>Boolean(l.capabilities?.includes('founder-content')&&Number(c.secretCount)>=4)
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||''))
const validClaim=(d,p)=>Boolean(d&&String(d.displayName||'').trim()&&validEmail(d.email)&&d.confirmed===true&&(!p||(d.fullName?.trim()&&d.address?.trim()&&d.addressNumber?.trim()&&d.postalCode?.trim()&&d.city?.trim()&&d.state?.trim()&&d.country?.trim()&&d.phone?.trim()&&d.physicalConsent===true)))
const publicStatus=(claim,eligible=false,isPhysical=false)=>({eligible,rewardUnlocked:eligible||Boolean(claim),rewardClaimed:Boolean(claim),...(claim?{rewardType:claim.reward_type,physicalEligible:claim.reward_type==='physical',claim:publicClaim(claim)}:eligible?{rewardType:isPhysical?'physical':'digital',physicalEligible:isPhysical}:{})})
const csvCell=value=>{let text=value==null?'':String(value);if(/^[=+\-@]/.test(text))text="'"+text;return`"${text.replaceAll('"','""')}"`}
const limiter=(limit,windowMs)=>{const map=new Map;return key=>{const now=Date.now(),item=map.get(key);if(!item||item.until<now){map.set(key,{count:1,until:now+windowMs});return true}if(item.count>=limit)return false;item.count++;return true}}
export function createRewardServer({cfg=loadConfig(),repo=new RewardRepository(cfg),email=new ResendEmailProvider(cfg),verifyLicense=verifyLicenseToken}={}){
 const claimAllowed=limiter(12,60_000),loginAllowed=limiter(6,15*60_000)
 const trustedOrigin=(r,origin)=>cfg.allowedOrigins.has(origin)||origin===`https://${r.headers.host}`
 const cors=r=>{const origin=r.headers.origin;return origin&&trustedOrigin(r,origin)?{'access-control-allow-origin':origin,vary:'Origin'}:{}}
 const admin=async r=>readSession(repo,cookies(r).cipher_admin,cfg.sessionSecret)
 return createServer(async(r,s)=>{const url=new URL(r.url,'http://service'),origin=r.headers.origin,ip=r.socket.remoteAddress||'unknown'
  try{
   if(r.method==='OPTIONS'){if(!origin||!trustedOrigin(r,origin))return json(r,s,403,{code:'ORIGIN_DENIED'});s.writeHead(204,{...cors(r),'access-control-allow-methods':'GET, POST, PATCH, OPTIONS','access-control-allow-headers':'content-type, authorization, idempotency-key','access-control-allow-credentials':'true'});return s.end()}
   if(origin&&!trustedOrigin(r,origin))return json(r,s,403,{code:'ORIGIN_DENIED'})
   if(r.method==='GET'&&url.pathname==='/health'){try{await repo.health();return json(r,s,200,{status:'ok'})}catch{return json(r,s,503,{status:'unavailable'})}}
   if(r.method==='GET'&&url.pathname==='/v1/reward/status'){const license=verifyLicense(bearer(r));if(!license)return json(r,s,401,{code:'UNAUTHORIZED'},cors(r));return json(r,s,200,publicStatus(await repo.findByLicense(license.licenseId)),cors(r))}
   if(r.method==='POST'&&url.pathname==='/v1/reward/eligibility'){const license=verifyLicense(bearer(r));if(!license)return json(r,s,401,{code:'UNAUTHORIZED'},cors(r));const input=await body(r);if(!complete(input.completion))return json(r,s,403,{eligible:false,rewardUnlocked:false,rewardClaimed:false},cors(r));const found=await repo.findByLicense(license.licenseId),isPhysical=physical(license,input.completion);return json(r,s,200,publicStatus(found,true,isPhysical),cors(r))}
   if(r.method==='POST'&&url.pathname==='/v1/reward/claim'){if(!claimAllowed(ip))return json(r,s,429,{code:'RATE_LIMITED'},cors(r));const license=verifyLicense(bearer(r));if(!license)return json(r,s,401,{code:'UNAUTHORIZED'},cors(r));const input=await body(r),completion=input.completion;if(!complete(completion))return json(r,s,403,{code:'NOT_ELIGIBLE'},cors(r));const isPhysical=physical(license,completion);if(!validClaim(input.data,isPhysical))return json(r,s,422,{code:'INVALID_CLAIM'},cors(r));if(String(r.headers['idempotency-key']||'')!==completion.completionId)return json(r,s,422,{code:'INVALID_IDEMPOTENCY_KEY'},cors(r));const idem=hash(`${license.licenseId}:${completion.completionId}`),now=new Date().toISOString();let claim;for(let attempt=0;attempt<4;attempt++){try{claim=await repo.createClaim({id:randomUUID(),license_id:license.licenseId,completion_id:completion.completionId,idempotency_key:idem,verification_code:`CIPHER-OP-${randomBytes(5).toString('hex').toUpperCase()}`,display_name:input.data.displayName.trim(),email:input.data.email.trim().toLowerCase(),license_type:license.type,founder_number:license.founderNumber||null,license_label:licenseLabel(license),completed_at:completion.completedAt,claimed_at:now,reward_type:isPhysical?'physical':'digital',full_name:isPhysical?input.data.fullName.trim():null,address:isPhysical?input.data.address.trim():null,address_number:isPhysical?input.data.addressNumber.trim():null,address_complement:isPhysical?String(input.data.addressComplement||'').trim():null,postal_code:isPhysical?input.data.postalCode.trim():null,city:isPhysical?input.data.city.trim():null,state:isPhysical?input.data.state.trim():null,country:isPhysical?input.data.country.trim():null,phone:isPhysical?input.data.phone.trim():null,physical_consent:isPhysical,notification_status:isPhysical?'PENDING':'NOT_REQUIRED'});break}catch(error){if(error.code!=='UNIQUE_CODE_COLLISION'||attempt===3)throw error}}
    if(isPhysical&&claim.notification_status!=='SENT'){try{await email.notifyPhysical(claim);await repo.markNotification(claim.id,'SENT')}catch(error){await repo.markNotification(claim.id,'FAILED');console.error(`[EMAIL] claimId=${claim.id} verificationCode=${claim.verification_code} error=${error?.message||'UNKNOWN'}`)}}
    return json(r,s,200,publicStatus(claim,true,isPhysical),cors(r))}
   if(r.method==='GET'&&url.pathname==='/admin/login')return html(s,loginHtml)
   if(r.method==='POST'&&url.pathname==='/v1/admin/login'){if(!loginAllowed(ip))return json(r,s,429,{code:'RATE_LIMITED'});const input=await body(r),ok=input.username===cfg.adminUsername&&await verifyAdminPassword(input.password,cfg.adminPasswordHash);if(!ok)return json(r,s,401,{code:'UNAUTHORIZED'});const session=await createSession(repo,input.username,cfg.sessionSecret),cookie=`cipher_admin=${encodeURIComponent(session.token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${cfg.production?'; Secure':''}`;return json(r,s,200,{authenticated:true},{'set-cookie':cookie})}
   if(r.method==='POST'&&url.pathname==='/v1/admin/logout'){const token=cookies(r).cipher_admin;await destroySession(repo,token,cfg.sessionSecret);return json(r,s,200,{authenticated:false},{'set-cookie':'cipher_admin=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'})}
   const session=await admin(r);if(url.pathname.startsWith('/v1/admin/')||url.pathname==='/admin/rewards'){if(!session)return url.pathname==='/admin/rewards'?(s.writeHead(302,{location:'/admin/login'}),s.end()):json(r,s,401,{code:'UNAUTHORIZED'})}
   if(r.method==='GET'&&url.pathname==='/admin/rewards')return html(s,adminHtml)
   if(r.method==='GET'&&url.pathname==='/v1/admin/rewards'){const status=STATUSES.has(url.searchParams.get('status'))?url.searchParams.get('status'):null,type=['FOUNDER','STANDARD','MASTER'].includes(url.searchParams.get('type'))?url.searchParams.get('type'):null;return json(r,s,200,{items:await repo.list({status,type,search:String(url.searchParams.get('search')||'').slice(0,100)})})}
   if(r.method==='GET'&&url.pathname==='/v1/admin/rewards.csv'){const items=await repo.list({status:null,type:null,search:''}),details=await Promise.all(items.map(x=>repo.detail(x.id))),columns=['verification_code','display_name','email','license_label','reward_type','full_name','address','address_number','address_complement','postal_code','city','state','country','phone','carrier','tracking_code','status','claimed_at'];const csv=[columns.join(','),...details.map(x=>columns.map(k=>csvCell(x[k])).join(','))].join('\r\n');s.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="cipher-rewards.csv"','cache-control':'no-store'});return s.end(csv)}
   const detail=/^\/v1\/admin\/rewards\/([0-9a-f-]+)$/.exec(url.pathname);if(r.method==='GET'&&detail){const claim=await repo.detail(detail[1]);return claim?json(r,s,200,claim):json(r,s,404,{code:'NOT_FOUND'})}
   const statusMatch=/^\/v1\/admin\/rewards\/([0-9a-f-]+)\/status$/.exec(url.pathname);if(r.method==='PATCH'&&statusMatch){const input=await body(r);if(!STATUSES.has(input.status))return json(r,s,422,{code:'INVALID_STATUS'});const claim=await repo.status(statusMatch[1],input.status);return claim?json(r,s,200,{id:claim.id,status:claim.status}):json(r,s,404,{code:'NOT_FOUND'})}
   const shipping=/^\/v1\/admin\/rewards\/([0-9a-f-]+)\/shipping$/.exec(url.pathname);if(r.method==='PATCH'&&shipping){const input=await body(r);if(input.trackingCode&&String(input.trackingCode).length>120)return json(r,s,422,{code:'INVALID_SHIPPING'});const claim=await repo.shipping(shipping[1],{carrier:String(input.carrier||'').slice(0,120),trackingCode:String(input.trackingCode||'').slice(0,120),adminNotes:String(input.adminNotes||'').slice(0,2000)});return claim?json(r,s,200,{id:claim.id,carrier:claim.carrier,trackingCode:claim.tracking_code}):json(r,s,404,{code:'NOT_FOUND'})}
   const notify=/^\/v1\/admin\/rewards\/([0-9a-f-]+)\/notify$/.exec(url.pathname);if(r.method==='POST'&&notify){const claim=await repo.detail(notify[1]);if(!claim||claim.reward_type!=='physical')return json(r,s,404,{code:'NOT_FOUND'});try{await email.notifyPhysical(claim);await repo.markNotification(claim.id,'SENT');return json(r,s,200,{id:claim.id,notificationStatus:'SENT'})}catch(error){await repo.markNotification(claim.id,'FAILED');console.error(`[EMAIL] claimId=${claim.id} verificationCode=${claim.verification_code} error=${error?.message||'UNKNOWN'}`);return json(r,s,502,{code:'EMAIL_UNAVAILABLE'})}}
   return json(r,s,404,{code:'NOT_FOUND'})
  }catch(error){const status=error.status||400;console.error(`[API] path=${url.pathname} error=${error?.message||'UNKNOWN'}`);return json(r,s,status,{code:status===413?'PAYLOAD_TOO_LARGE':'INVALID_REQUEST'})}})
}
export const isMainModule=(moduleUrl,entryPath)=>Boolean(entryPath&&moduleUrl===pathToFileURL(entryPath).href)
if(isMainModule(import.meta.url,process.argv[1])){const cfg=loadConfig(),server=createRewardServer({cfg});server.listen(cfg.port,'0.0.0.0',()=>console.log(`CIPHER Reward API listening on port ${cfg.port}`))}
