import{useEffect,useRef}from'react';import{SYSTEM_CONFIG}from'../../config/system';import type{NarrativeState,OperatorIdentity,TerminalLogType,TerminalSource}from'../../types'
const randomBetween=(min:number,max:number)=>Math.floor(Math.random()*(max-min+1))+min
interface Props{state:NarrativeState;firstDetectionCompleted:boolean;identity:OperatorIdentity;setState:(s:NarrativeState)=>void;addLog:(l:{source:TerminalSource;type:TerminalLogType;message:string})=>void;setInterference:(active:boolean)=>void}
export const shouldRunDetection=(state:NarrativeState,firstDetectionCompleted:boolean)=>state==='INITIAL'&&!firstDetectionCompleted
export function DetectionSequence({state,firstDetectionCompleted,identity,setState,addLog,setInterference}:Props){
 const identityRef=useRef(identity);useEffect(()=>{identityRef.current=identity},[identity])
 useEffect(()=>{if(shouldRunDetection(state,firstDetectionCompleted))void setState('MONITORING')},[state,firstDetectionCompleted,setState])
 useEffect(()=>{if(state!=='MONITORING')return;const timer=window.setTimeout(()=>setState('ANOMALY'),randomBetween(SYSTEM_CONFIG.detectionDelay.min,SYSTEM_CONFIG.detectionDelay.max));return()=>clearTimeout(timer)},[state,setState])
 useEffect(()=>{if(state!=='ANOMALY')return;setInterference(true);addLog({source:'ORPHEUS',type:'info',message:'Verificando integridade da sessão...'});const timers:number[]=[];const later=(delay:number,fn:()=>void)=>timers.push(window.setTimeout(fn,delay));later(900,()=>addLog({source:'SYSTEM',type:'system',message:'Identidade da sessão inconsistente.'}));later(1800,()=>addLog({source:'WARNING',type:'warning',message:'Assinatura externa detectada.'}));later(2700,()=>addLog({source:'ORPHEUS',type:'info',message:'Executando identificação local...'}));later(3300,()=>addLog({source:'SYSTEM',type:'system',message:`PLATAFORMA: ${identityRef.current.platform.toUpperCase()} // ARQUITETURA: ${identityRef.current.arch.toUpperCase()}`}));later(3800,()=>{setInterference(false);addLog({source:'ORPHEUS',type:'success',message:`HOST IDENTIFICADO: ${identityRef.current.hostname}`})});later(4700,()=>addLog({source:'CIPHER',type:'cipher',message:`OPERADOR IDENTIFICADO: ${identityRef.current.username}`}));later(5700,()=>{addLog({source:'WARNING',type:'danger',message:'ESTA SESSÃO NÃO ESTAVA PREVISTA.'});setState('DETECTED')});return()=>timers.forEach(clearTimeout)},[state,setState,addLog,setInterference])
 return null
}
