import { formatFounderAccess } from '../../config/system'
import type { EnigmaStatus } from '../../types'
import type { CommandContext, OrpheusCommand } from './commandTypes'

const line=(label:string,value:string)=>`${label.padEnd(20,'.')} ${value}`
const missionActive=(context:CommandContext)=>context.progress.missionStarted
const statusLabel:Record<EnigmaStatus,string>={locked:'LOCKED',available:'AVAILABLE',active:'ACTIVE',solved:'SOLVED'}
const enigmaName=(title:string)=>title.replace(/^Enigma\s+\d+\s+—\s+/i,'').toUpperCase()

export const commandRegistry:OrpheusCommand[]=[
 {name:'help',description:'lista comandos disponíveis',execute:()=>({output:`ORPHEUS COMMAND INDEX\n\n${getPublicCommands().map(command=>`${command.name.padEnd(20)}${command.description}`).join('\n')}`})},
 {name:'status',description:'estado atual do sistema',execute:(_,context)=>({output:`ORPHEUS SYSTEM STATUS\n\n${line('CORE','ONLINE')}\n${line('CIPHER NODE','ACTIVE')}\n${line('SESSION','SECURE')}\n${line('THREAT LEVEL','ELEVATED')}\n${line('OPERATOR',context.progress.operator.username.toUpperCase())}\n${line('MISSION',missionActive(context)?'ACTIVE':'STANDBY')}\n${line('NARRATIVE STATE',context.progress.narrativeState)}\n${line('FILES',`${context.progress.restoredFragments.length}/12`)}\n${line('FOUNDERS ACCESS',formatFounderAccess(context.progress.founderId,context.progress.founderTotal))}`})},
 {name:'whoami',aliases:['id'],description:'identifica o operador',execute:(_,context)=>({output:`IDENTITY CONFIRMED\n\n${line('OPERADOR',context.progress.operator.username.toUpperCase())}\n${line('ACCESS','CIPHER')}\n${line('FOUNDERS',formatFounderAccess(context.progress.founderId,context.progress.founderTotal))}\n${line('STATUS',missionActive(context)?'ACTIVE':'MONITORING')}`})},
 {name:'host',description:'informações do host',execute:(_,context)=>({output:`LOCAL NODE\n\n${line('HOSTNAME',context.progress.operator.hostname.toUpperCase())}\n${line('PLATFORM',context.progress.operator.platform.toUpperCase())}\n${line('ARCHITECTURE',context.progress.operator.arch.toUpperCase())}`})},
 {name:'mission',aliases:['missions'],description:'objetivo atual',execute:(_,context)=>({output:`CURRENT OBJECTIVE\n\n${missionActive(context)?'Recuperar a primeira chave narrativa e identificar\no padrão por trás do Protocolo Orpheus.':'Monitorar a integridade da sessão e aguardar\nnovas instruções do sistema.'}\n\nSTATUS: ${missionActive(context)?'EM ANDAMENTO':'MONITORANDO'}`,actions:[{type:'highlight-objective'}]})},
 {name:'enigmas',description:'lista Caixas Enigmas',execute:(_,context)=>({output:`CAIXAS ENIGMAS\n\n${context.enigmas.map(enigma=>`${String(enigma.number).padStart(2,'0')}  ${enigmaName(enigma.title).padEnd(22,'.')} ${statusLabel[enigma.status]}`).join('\n')}`})},
 {name:'hint',description:'solicita pista de uma Caixa',execute:(args,context)=>{const number=Number.parseInt(args[0]??'',10);const enigma=context.enigmas.find(item=>item.number===number);if(!enigma)return{output:'USAGE\n\nhint 01',tone:'warning'};if(enigma.status==='locked')return{output:'HINT ACCESS DENIED.\n\nENIGMA IS LOCKED.',tone:'danger'};return{output:'ANALYZING HINT ACCESS...',delayMs:250,pendingText:'ACCESSING...',actions:[{type:'request-hint',enigmaId:enigma.id}]}}},
 {name:'answer',description:'valida resposta de uma Caixa',execute:(args,context)=>{const number=Number.parseInt(args[0]??'',10);const enigma=context.enigmas.find(item=>item.number===number);const answer=args.slice(1).join(' ');if(!enigma||!answer)return{output:'USAGE\n\nanswer 01 <resposta>',tone:'warning',sensitive:true};if(enigma.status==='locked')return{output:'ACCESS DENIED.\n\nENIGMA IS LOCKED.',tone:'danger',sensitive:true};return{output:'VALIDATING...',delayMs:300,pendingText:'CIPHER CHECK...',actions:[{type:'submit-answer',enigmaId:enigma.id,answer}],sensitive:true}}},
 {name:'open',description:'abre recurso disponível',execute:(args,context)=>{if(args[0]?.toLowerCase()==='file'){const fileNumber=(args[1]??'').padStart(2,'0');const available=context.progress.unlockedFiles.some(file=>file===fileNumber||file.endsWith(fileNumber));return available?{output:`ACCESS GRANTED\nOPENING FILE ${fileNumber}...`,tone:'success',actions:[{type:'navigate',destination:'Arquivos'}]}:{output:`ACCESS DENIED\n\nFILE ${fileNumber} IS NOT AVAILABLE.`,tone:'danger'}}const clean=args[0]?.toLowerCase()==='enigma'?args.slice(1):args;const number=Number.parseInt(clean[0]??'',10);if(!Number.isFinite(number))return{output:'USAGE\n\nopen enigma 01\nopen 01\nopen file 03',tone:'warning'};const enigma=context.enigmas.find(item=>item.number===number);if(!enigma)return{output:`RESOURCE NOT FOUND\n\nENIGMA ${String(number).padStart(2,'0')} IS NOT REGISTERED.`,tone:'warning'};if(enigma.status==='locked')return{output:`ACCESS DENIED\n\nENIGMA ${String(number).padStart(2,'0')} IS LOCKED.\nPREREQUISITE NOT SATISFIED.`,tone:'danger'};return{output:`ACCESS GRANTED\nOPENING ENIGMA ${String(number).padStart(2,'0')}...`,tone:'success',delayMs:250,pendingText:'ACCESSING...',actions:[{type:'open-enigma',enigmaId:enigma.id}]}}},
 {name:'files',description:'arquivos recuperados',execute:(_,context)=>({output:`RECOVERED FILE INDEX\n\n${context.progress.restoredFragments.length} / 12 fragments restored${context.progress.unlockedFiles.length?`\n\n${context.progress.unlockedFiles.join('\n')}`:''}`})},
 {name:'messages',aliases:['msg'],description:'mensagens disponíveis',execute:()=>({output:'MESSAGE INDEX\n\n[PLACEHOLDER] Nenhuma mensagem narrativa validada nesta build.'})},
 {name:'read',description:'lê mensagem disponível',execute:(args)=>(args[0]?.toLowerCase()==='message'&&args[1]?{output:`MESSAGE ${args[1].padStart(2,'0')}\n\n[PLACEHOLDER] Conteúdo temporário; nenhuma mensagem canônica foi adicionada.`}:{output:'USAGE\n\nread message 01',tone:'warning'})},
 {name:'dossier',description:'consulta dossiês',execute:(args)=>{const subjects=['blake','evelyn','gordon','cipher','orpheus'];const subject=args[0]?.toLowerCase();if(!subject)return{output:`USAGE\n\n${subjects.map(item=>`dossier ${item}`).join('\n')}`};if(!subjects.includes(subject))return{output:'DOSSIER NOT FOUND.\n\nCLASSIFIED INDEX RETURNED NO MATCH.',tone:'warning',delayMs:300,pendingText:'SEARCHING CLASSIFIED INDEX...'};return{output:'DOSSIER FOUND.',tone:'success',delayMs:450,pendingText:'SEARCHING CLASSIFIED INDEX...',actions:[{type:'open-dossier',subject}]}}},
 {name:'search',description:'Pesquisa Profunda',execute:(args)=>args.length?{output:`QUERY PREPARED\n\n${args.join(' ')}`,delayMs:250,pendingText:'INDEXING QUERY...',actions:[{type:'prepare-search',query:args.join(' ')}]}:{output:'USAGE\n\nsearch "Empresa XYZ"',tone:'warning'}},
 {name:'deepsearch',description:'executa pesquisa OSINT profunda',execute:(args)=>args.length?{output:`DEEP SEARCH INITIALIZED.\n\nTARGET: ${args.join(' ')}\nOPENING INVESTIGATION WORKSPACE...`,delayMs:300,pendingText:'PLANNING...',actions:[{type:'osint',action:'run',query:args.join(' '),mode:'deep'}]}:{output:'USAGE\n\ndeepsearch "Empresa XYZ"',tone:'warning'}},
 {name:'correlate',description:'correlaciona resultados OSINT',execute:()=>({output:'CORRELATING CURRENT INVESTIGATION...',delayMs:250,pendingText:'CORRELATING...',actions:[{type:'osint',action:'correlate'}]})},
 {name:'investigation',description:'abre investigação atual',execute:()=>({output:'OPENING INVESTIGATION WORKSPACE...',actions:[{type:'osint',action:'investigation'}]})},
 {name:'entities',description:'lista entidades investigativas',execute:()=>({output:'OPENING ENTITY INDEX...',actions:[{type:'osint',action:'entities'}]})},
 {name:'relationships',aliases:['links'],description:'lista relações e evidências',execute:()=>({output:'OPENING RELATIONSHIP INDEX...',actions:[{type:'osint',action:'relationships'}]})},
 {name:'timeline',description:'abre timeline investigativa',execute:()=>({output:'OPENING VERIFIED TIMELINE...',actions:[{type:'osint',action:'timeline'}]})},
 {name:'graph',description:'abre grafo investigativo',execute:()=>({output:'RENDERING INVESTIGATION GRAPH...',actions:[{type:'osint',action:'graph'}]})},
 {name:'evidence',description:'lista evidências rastreáveis',execute:()=>({output:'OPENING EVIDENCE INDEX...',actions:[{type:'osint',action:'evidence'}]})},
 {name:'report',description:'gera relatório OSINT preliminar',execute:()=>({output:'PRELIMINARY REPORT PREPARED.',actions:[{type:'osint',action:'report'}]})},
 {name:'export',description:'exporta investigação em JSON ou CSV',execute:(args)=>args[0]==='json'||args[0]==='csv'?{output:`EXPORT ${args[0].toUpperCase()} PREPARED.`,actions:[{type:'osint',action:'export',format:args[0]}]}:{output:'USAGE\n\nexport json\nexport csv',tone:'warning'}},
 {name:'clear',aliases:['cls'],description:'limpa terminal',execute:()=>({output:'',actions:[{type:'clear'}]})},
 {name:'history',description:'histórico de comandos',execute:(_,context)=>({output:`COMMAND HISTORY\n\n${context.history.length?context.history.map((item,index)=>`${String(index+1).padStart(2,'0')}  ${item}`).join('\n'):'NO COMMANDS IN CURRENT SESSION.'}`})},
 {name:'about',description:'informações do ORPHEUS',execute:()=>({output:'ORPHEUS INTELLIGENCE SYSTEM\nCIPHER ACCESS NODE\nCOMPANION EXPERIENCE'})},
 {name:'privacy',description:'política local de privacidade',execute:()=>({output:'OPENING LOCAL PRIVACY POLICY...',actions:[{type:'navigate',destination:'Privacidade'}]})},
 {name:'dork',description:'abre Deep Dorks',execute:(args)=>({output:'OPENING DEEP DORKS MODULE...',actions:[{type:'osint',action:'prepare',query:args.join(' '),mode:'dork'}]})},
 {name:'trace',description:'destaca relações conhecidas no grafo',execute:(args)=>({output:`TRACE RELATIONSHIPS${args.length?`\n\nTARGET: ${args.join(' ')}`:''}`,actions:[{type:'osint',action:'trace',query:args.join(' ')}]})},
]

export function getPublicCommands(){return commandRegistry.filter(command=>!command.hidden)}
export function findCommand(name:string){const normalized=name.toLowerCase();return commandRegistry.find(command=>command.name===normalized||command.aliases?.includes(normalized))}
