import test,{after,before,beforeEach}from'node:test';import assert from'node:assert/strict';import{scryptSync,randomBytes}from'node:crypto';import{pathToFileURL}from'node:url';import{createRewardServer,isMainModule}from'../src/server.mjs'
class MemoryRepo{constructor(){this.claims=[];this.sessions=new Map;this.failCreate=false}async health(){}async findByLicense(id){return this.claims.find(x=>x.license_id===id)||null}async createClaim(v){if(this.failCreate)throw Error('DB_DOWN');const found=await this.findByLicense(v.license_id);if(found)return found;this.claims.push({...v,reward_edit_count:0,status:'PENDING',shipping_status:'PENDING'});return this.claims.at(-1)}async markNotification(id,status){this.claims.find(x=>x.id===id).notification_status=status}async list({status,type,search}){return this.claims.filter(x=>(!status||x.status===status)&&(!type||x.license_type===type)&&(!search||x.verification_code.includes(search)||x.display_name.includes(search)))}async detail(id){return this.claims.find(x=>x.id===id)||null}async status(id,status){const x=await this.detail(id);if(x)x.status=x.shipping_status=status;return x}async shipping(id,v){const x=await this.detail(id);if(x){x.carrier=v.carrier;x.tracking_code=v.trackingCode;x.admin_notes=v.adminNotes}return x}async createSession(h,u,e){this.sessions.set(h,{username:u,expiresAt:e})}async session(h){const x=this.sessions.get(h);return x&&x.expiresAt>new Date()?x:null}async deleteSession(h){this.sessions.delete(h)}}
const salt=randomBytes(16),passwordHash=`scrypt$${salt.toString('hex')}$${scryptSync('correct horse',salt,64).toString('hex')}`,cfg={production:false,allowedOrigins:new Set(['tauri://localhost']),adminUsername:'cipher-admin',adminPasswordHash:passwordHash,sessionSecret:'test-secret',adminEmail:'admin@example.test',emailFrom:'cipher@example.test',resendApiKey:'test',adminBaseUrl:'http://test'}
const licenses={standard:{licenseId:'LIC-STD',type:'STANDARD',status:'active',capabilities:['orpheus-core']},founder:{licenseId:'LIC-F07',type:'FOUNDER',founderNumber:7,status:'active',capabilities:['orpheus-core','founder-content']}}
const proof=(valid=true,secrets=0)=>({completionId:'completion-1',completedAt:'2026-08-24T20:00:00Z',campaignCompleted:valid,progress:valid?100:99,solvedIds:Array.from({length:valid?12:11},(_,i)=>`box-${String(i+1).padStart(2,'0')}`),secretCount:secrets})
const data=(physical=false)=>({displayName:'Operator',email:'operator@example.test',confirmed:true,...physical?{fullName:'Operator Test',address:'Test Street',addressNumber:'7',addressComplement:'A',postalCode:'00000-000',city:'Test',state:'TS',country:'BR',phone:'+550000000000',physicalConsent:true}:{}})
let repo,email,server,base
before(async()=>{server=createRewardServer({cfg,repo:repo=new MemoryRepo,email:email={calls:0,fail:false,async notifyPhysical(){this.calls++;if(this.fail)throw Error('EMAIL_DOWN')}},verifyLicense:t=>licenses[t]||null});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`})
after(()=>new Promise(r=>server.close(r)))
beforeEach(()=>{repo.claims=[];repo.sessions.clear();repo.failCreate=false;email.calls=0;email.fail=false})
const request=(path,{token,body,method='POST',cookie,idem='completion-1'}={})=>fetch(base+path,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{}),...(body?{'content-type':'application/json'}:{}),...(idem?{'idempotency-key':idem}:{}),...(cookie?{cookie}:{})},...(body?{body:JSON.stringify(body)}:{})})
test('health checks database without details',async()=>assert.deepEqual(await(await request('/health',{method:'GET',idem:null})).json(),{status:'ok'}))
test('valid Standard claim is digital and public response has no PII',async()=>{const x=await(await request('/v1/reward/claim',{token:'standard',body:{completion:proof(),data:data()}})).json();assert.equal(x.claim.rewardType,'digital');for(const k of['email','address','phone','shipping'])assert.equal(Object.hasOwn(x.claim,k),false)})
test('invalid license and completion are rejected',async()=>{assert.equal((await request('/v1/reward/claim',{token:'bad',body:{completion:proof(),data:data()}})).status,401);assert.equal((await request('/v1/reward/claim',{token:'standard',body:{completion:proof(false),data:data()}})).status,403)})
test('invalid data is rejected',async()=>assert.equal((await request('/v1/reward/claim',{token:'standard',body:{completion:proof(),data:{displayName:'',email:'bad'}}})).status,422))
test('duplicate and concurrent requests create one claim',async()=>{const args={token:'standard',body:{completion:proof(),data:data()}};const[a,b]=await Promise.all([request('/v1/reward/claim',args),request('/v1/reward/claim',args)]);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(repo.claims.length,1);assert.equal((await a.json()).claim.verificationCode,(await b.json()).claim.verificationCode)})
test('Founder physical claim sends notification and preserves numbering',async()=>{const x=await(await request('/v1/reward/claim',{token:'founder',body:{completion:proof(true,4),data:data(true)}})).json();assert.equal(x.claim.rewardType,'physical');assert.equal(x.claim.licenseLabel,'Founder 07/30');assert.equal(email.calls,1)})
test('email failure does not remove committed claim',async()=>{email.fail=true;const r=await request('/v1/reward/claim',{token:'founder',body:{completion:proof(true,4),data:data(true)}});assert.equal(r.status,200);assert.equal(repo.claims.length,1);assert.equal(repo.claims[0].notification_status,'FAILED')})
test('database failure creates no partial claim',async()=>{repo.failCreate=true;assert.equal((await request('/v1/reward/claim',{token:'standard',body:{completion:proof(),data:data()}})).status,400);assert.equal(repo.claims.length,0)})
async function login(){const r=await request('/v1/admin/login',{body:{username:'cipher-admin',password:'correct horse'},idem:null});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0]}
test('admin endpoints require a server session',async()=>assert.equal((await request('/v1/admin/rewards',{method:'GET',idem:null})).status,401))
test('admin session lists, details and CSV',async()=>{await request('/v1/reward/claim',{token:'standard',body:{completion:proof(),data:data()}});const cookie=await login();assert.equal((await request('/v1/admin/rewards',{method:'GET',cookie,idem:null})).status,200);assert.equal((await request(`/v1/admin/rewards/${repo.claims[0].id}`,{method:'GET',cookie,idem:null})).status,200);assert.equal((await request('/v1/admin/rewards.csv',{method:'GET',cookie,idem:null})).status,200)})
test('admin changes controlled status and shipping tracking',async()=>{await request('/v1/reward/claim',{token:'founder',body:{completion:proof(true,4),data:data(true)}});const cookie=await login(),id=repo.claims[0].id;assert.equal((await request(`/v1/admin/rewards/${id}/status`,{method:'PATCH',cookie,body:{status:'SHIPPED'},idem:null})).status,200);assert.equal((await request(`/v1/admin/rewards/${id}/shipping`,{method:'PATCH',cookie,body:{carrier:'Carrier',trackingCode:'TRACK-1'},idem:null})).status,200);assert.equal(repo.claims[0].tracking_code,'TRACK-1')})
test('public status never returns stored PII',async()=>{await request('/v1/reward/claim',{token:'standard',body:{completion:proof(),data:data()}});const text=await(await request('/v1/reward/status',{method:'GET',token:'standard',idem:null})).text();assert.equal(text.includes('operator@example.test'),false);assert.equal(text.includes('Test Street'),false)})

test('entrypoint detection accepts a Windows path through pathToFileURL',()=>{const entry='C:\\opt\\render\\project\\src\\reward-api\\src\\server.mjs';assert.equal(isMainModule(pathToFileURL(entry).href,entry),true)})
test('entrypoint detection accepts a POSIX/Linux path through pathToFileURL',()=>{const entry='/opt/render/project/src/reward-api/src/server.mjs';assert.equal(isMainModule(pathToFileURL(entry).href,entry),true)})
test('entrypoint detection rejects a different module and an absent argv entry',()=>{const entry='/opt/render/project/src/reward-api/src/server.mjs';assert.equal(isMainModule(pathToFileURL('/different/server.mjs').href,entry),false);assert.equal(isMainModule(pathToFileURL(entry).href,undefined),false)})