import type{Investigation,InvestigationSnapshot}from'../types/investigation';import{summarizeInvestigation}from'./investigationEngine'
const disclaimer='Este relatório contém correlações baseadas em informações de fontes públicas. Correlação não estabelece identidade nem prática de irregularidade.'
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
export function snapshotInvestigation(item:Investigation):InvestigationSnapshot{return{investigation:{version:item.version,id:item.id,target:item.target,createdAt:item.createdAt,updatedAt:item.updatedAt},entities:item.entities,relationships:item.relationships,evidence:item.evidence,timeline:item.timeline,hypotheses:item.hypotheses,limitations:[disclaimer,'Datas ausentes são exibidas como desconhecidas; nenhuma data é inferida.']}}
export function investigationJson(item:Investigation){return JSON.stringify(snapshotInvestigation(item),null,2)}
const csv=(rows:Record<string,unknown>[])=>{const keys=[...new Set(rows.flatMap(Object.keys))];const cell=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;return[keys.map(cell).join(','),...rows.map(row=>keys.map(key=>cell(row[key])).join(','))].join('\n')}
export function investigationCsv(item:Investigation,type:'entities'|'relationships'|'timeline'){if(type==='entities')return csv(item.entities.map(({id,type,label,confidence,sourceIds})=>({id,type,label,confidence,sources:sourceIds.join('|')})));if(type==='relationships')return csv(item.relationships.map(({id,sourceEntityId,targetEntityId,type,confidence,score,reviewStatus,explanation})=>({id,sourceEntityId,targetEntityId,type,confidence,score,reviewStatus,explanation})));return csv(item.timeline.map(({id,date,precision,title,sourceId,entityIds})=>({id,date,precision,title,sourceId,entities:entityIds.join('|')})))}
export function investigationHtml(item:Investigation){const summary=summarizeInvestigation(item);const rows=item.relationships.map(link=>`<tr><td>${escape(link.type)}</td><td>${escape(link.confidence.toUpperCase())}</td><td>${escape(link.explanation)}</td><td>${escape(link.reviewStatus)}</td></tr>`).join('');return`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>ORPHEUS Investigation Report</title><style>body{background:#071017;color:#d7e8ee;font:14px system-ui;padding:40px}h1,h2{color:#58d8ef}table{width:100%;border-collapse:collapse}td,th{padding:10px;border:1px solid #23414c;text-align:left}.notice{border-left:3px solid #df4055;padding:12px;background:#101b22}</style><h1>ORPHEUS INVESTIGATION REPORT</h1><p>Target: ${escape(item.target)}</p><h2>Executive Summary</h2><p>${summary.results} resultados, ${summary.entities} entidades e ${summary.relationships} relações rastreáveis.</p><h2>Sources</h2><p>${escape([...new Set(item.sourceSession.results.map(r=>r.source))].join(', ')||'Nenhuma fonte disponível.')}</p><h2>Entities</h2><ul>${item.entities.map(e=>`<li>${escape(e.type.toUpperCase())}: ${escape(e.label)} — ${escape(e.confidence.toUpperCase())}</li>`).join('')}</ul><h2>Relationships & Evidence</h2><table><tr><th>Type</th><th>Confidence</th><th>Evidence</th><th>Review</th></tr>${rows}</table><h2>Timeline</h2><ul>${item.timeline.map(e=>`<li>${escape(e.date)} — ${escape(e.title)}</li>`).join('')}</ul><h2>Operator Hypotheses</h2><ul>${item.hypotheses.map(h=>`<li>OPERATOR HYPOTHESIS: ${escape(h.text)}</li>`).join('')}</ul><h2>Limitations</h2><p class="notice">${escape(disclaimer)}</p></html>`}
export function downloadInvestigation(item:Investigation,format:'json'|'html'|'entities'|'relationships'|'timeline'){const content=format==='json'?investigationJson(item):format==='html'?investigationHtml(item):investigationCsv(item,format);const mime=format==='html'?'text/html':format==='json'?'application/json':'text/csv';const ext=format==='html'?'html':format==='json'?'json':'csv';const url=URL.createObjectURL(new Blob([content],{type:`${mime};charset=utf-8`}));const link=document.createElement('a');link.href=url;link.download=`orpheus-${item.id}-${format}.${ext}`;link.click();URL.revokeObjectURL(url)}
