import{useEffect,useRef,useState}from'react'
import{Icon}from'../../../components/Icon'
import{validateDork}from'../engine/dorkBuilder'
import{createSearchPlan}from'../engine/queryPlanner'
import{detectTarget}from'../engine/queryNormalizer'
import{openExternalUrl,webSearchUrl}from'../engine/searchLinks'
import{useOsintInvestigation}from'../hooks/useOsintInvestigation'
import type{SearchMode}from'../types/osint'
import{CorrelationPanel}from'./CorrelationPanel';import{DorkBuilder}from'./DorkBuilder';import{downloadSession,ExportPanel}from'./ExportPanel';import{SearchInput}from'./SearchInput';import{SearchPlan}from'./SearchPlan';import{SearchResults}from'./SearchResults';import{SourceStatus}from'./SourceStatus';import styles from'./DeepSearchPanel.module.css'

export interface OsintRequest{nonce:number;query?:string;mode?:SearchMode;action?:'prepare'|'run'|'correlate'|'report'|'export';format?:'json'|'csv'}
type AuditEvent='SEARCH_STARTED'|'SEARCH_COMPLETED'|'SEARCH_CANCELLED'|'RESULT_OPENED'|'REPORT_CREATED'
export function DeepSearchPanel({initialQuery='',initialMode='quick',request,onAudit}:{initialQuery?:string;initialMode?:SearchMode;request?:OsintRequest;onAudit?:(event:AuditEvent,resource?:string)=>void}){
 const[query,setQuery]=useState(initialQuery);const[mode,setMode]=useState<SearchMode>(initialMode);const[privateMode,setPrivateMode]=useState(false);const state=useOsintInvestigation();const lastRequest=useRef(0);const plan=query?createSearchPlan(detectTarget(query),mode):[]
 const execute=async()=>{if(!query.trim())return;if(mode==='dork'&&!validateDork(query).allowed)return;onAudit?.('SEARCH_STARTED',detectTarget(query).type);const result=await state.search(query,mode,privateMode);onAudit?.(result?'SEARCH_COMPLETED':'SEARCH_CANCELLED',result?.targetType)}
 useEffect(()=>{if(!state.noticeAccepted||!request||request.nonce===lastRequest.current)return;if(['correlate','report','export'].includes(request.action??'')&&!state.session)return;lastRequest.current=request.nonce;if(request.query!==undefined)setQuery(request.query);if(request.mode)setMode(request.mode);if(request.action==='run'&&request.query){onAudit?.('SEARCH_STARTED',detectTarget(request.query).type);queueMicrotask(()=>void state.search(request.query!,request.mode??'quick',privateMode).then(result=>onAudit?.(result?'SEARCH_COMPLETED':'SEARCH_CANCELLED',result?.targetType)))}if(request.action==='correlate')state.correlate();if(request.action==='report'&&state.session)onAudit?.('REPORT_CREATED',state.session.id);if(request.action==='export'&&request.format&&state.session)downloadSession(state.session,request.format)},[request,state,privateMode,onAudit])
 if(!state.noticeAccepted)return <section className={styles.panel}><header className={styles.hero}><Icon name="search" size={25}/><div><small>ORPHEUS // OSINT NOTICE</small><h1>ORPHEUS OSINT</h1></div></header><div className={styles.notice}><p>Utilize apenas fontes públicas e dados que você tenha autorização legal para consultar.</p><p>O ORPHEUS não fornece acesso a sistemas privados.</p><button onClick={()=>void state.acceptNotice()}>COMPREENDIDO</button></div></section>
 return <section className={styles.panel}><header className={styles.hero}><Icon name={mode==='dork'?'terminal':'search'} size={25}/><div><small>ORPHEUS // SEARCH.05</small><h1>{mode==='dork'?'DEEP DORKS':'ORPHEUS DEEP SEARCH'}</h1></div><b>{import.meta.env.DEV?'DEV PROVIDER ACTIVE':'PUBLIC PROVIDERS ONLY'}</b></header>{mode==='dork'&&<DorkBuilder value={query} onChange={setQuery}/>}<SearchInput query={query} setQuery={setQuery} mode={mode} setMode={setMode} privateMode={privateMode} setPrivateMode={setPrivateMode} busy={state.busy} onSearch={()=>void execute()} onCancel={()=>{state.cancel();onAudit?.('SEARCH_CANCELLED')}}/>{state.error&&<div className={styles.error}>{state.error}</div>}<div className={styles.columns}><SearchPlan plan={state.session?.plan??plan} onOpen={value=>void openExternalUrl(webSearchUrl(value))}/><SourceStatus items={state.statuses.length?state.statuses:state.session?.providers??[]}/></div>{state.session&&<><div className={styles.summary}><span>TARGET <b>{state.session.query}</b></span><span>TYPE <b>{state.session.targetType.toUpperCase()}</b></span><span>MODE <b>{state.session.mode.toUpperCase()}</b></span><span>{state.session.results.length} UNIQUE RESULTS</span></div>{!state.session.results.length&&<div className={styles.noProvider}>NO SEARCH PROVIDER CONFIGURED FOR THIS TARGET.<br/><small>Use ABRIR in the search plan to continue manual e legitimamente no navegador padrão.</small></div>}<SearchResults results={state.session.results} onOpen={url=>{onAudit?.('RESULT_OPENED');void openExternalUrl(url)}}/><CorrelationPanel items={state.session.correlations}/><ExportPanel session={state.session}/></>}<section className={styles.history}><header>HISTÓRICO DE PESQUISAS</header>{state.history.map(item=><button key={item.id} onClick={()=>state.setSession(item)}><span>{item.query}</span><small>{item.mode.toUpperCase()} // {new Date(item.createdAt).toLocaleString('pt-BR')}</small><i onClick={event=>{event.stopPropagation();void state.remove(item.id)}}>LIMPAR OPERAÇÃO</i></button>)}</section></section>
}
