import{useEffect,useState}from'react'
import type{Enigma}from'../../types'
import type{HintAccessResult,ValidationResult}from'./engine/enigmaTypes'
import{Icon}from'../../components/Icon'
import{loadCanonicalEnigmaContent,revealCanonicalHint,type CanonicalEnigmaContent}from'./services/canonicalContent'
import styles from'./EnigmaModal.module.css'
type DevAction='unlock'|'lock'|'solve'|'reset'|'attempt'|'hint'
type LoadState='loading'|'ready'|'unavailable'
export function EnigmaModal({enigma,onClose,onSubmit,onHint,onDevAction}:{enigma:Enigma;onClose:()=>void;onSubmit:(answer:string)=>Promise<ValidationResult>;onHint:()=>Promise<HintAccessResult>;onDevAction?:(action:DevAction)=>void}){
 const[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[hintBusy,setHintBusy]=useState(false),[result,setResult]=useState<ValidationResult|null>(null),[hintMessage,setHintMessage]=useState(''),[revealedHints,setRevealedHints]=useState<Record<number,string>>({}),[content,setContent]=useState<CanonicalEnigmaContent|null>(null),[loadState,setLoadState]=useState<LoadState>('loading')
 useEffect(()=>{const controller=new AbortController();setContent(null);setRevealedHints({});setLoadState('loading');void loadCanonicalEnigmaContent(enigma.id,controller.signal).then(async value=>{if(controller.signal.aborted)return;setContent(value);setLoadState(value?'ready':'unavailable');if(!value)return;const count=Math.min(enigma.hintsUnlocked.length,value.hintCount),items=await Promise.all(Array.from({length:count},(_,index)=>revealCanonicalHint(enigma.id,index+1,controller.signal)));if(controller.signal.aborted)return;setRevealedHints(Object.fromEntries(items.filter(item=>item).map(item=>[item!.index,item!.text]))) });return()=>controller.abort()},[enigma.id])
 const playable=loadState==='ready'&&Boolean(content?.question.trim()),evidence=content?.evidence??[],allHints=Boolean(content&&enigma.hintsUnlocked.length>=content.hintCount)
 const validate=async()=>{if(!playable||!answer.trim()||busy)return;setBusy(true);setResult(null);const response=await onSubmit(answer);setAnswer('');setResult(response);setBusy(false)}
 const requestHint=async()=>{if(!playable||hintBusy||!content)return;if(allHints){setHintMessage('TODAS AS PISTAS LIBERADAS');return}const hintIndex=enigma.hintsUnlocked.length+1;setHintBusy(true);setHintMessage('');const revealed=await revealCanonicalHint(enigma.id,hintIndex);if(!revealed){setHintMessage('CANAL DE PISTAS TEMPORARIAMENTE INDISPONÍVEL. TENTE NOVAMENTE.');setHintBusy(false);return}const access=await onHint();if(access.allowed){setRevealedHints(current=>({...current,[revealed.index]:revealed.text}));setHintMessage(enigma.hintsUnlocked.length+1>=content.hintCount?'TODAS AS PISTAS LIBERADAS':`${revealed.label} LIBERADA`)}else setHintMessage(access.reason==='ALL_UNLOCKED'?'TODAS AS PISTAS LIBERADAS':'PISTA INDISPONÍVEL');setHintBusy(false)}
 return <div className={styles.backdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="enigma-title"><div className={styles.scan}/><header><div><small>CAIXA ENIGMA {String(enigma.number).padStart(2,'0')}</small><h2 id="enigma-title">{content?.title??enigma.title}</h2></div><button onClick={onClose} aria-label="Fechar"><Icon name="close"/></button></header><div className={styles.grid}><div><small>CLASSIFICAÇÃO</small><strong>{enigma.subtitle}</strong></div><div><small>STATUS</small><strong>{enigma.status.toUpperCase()}</strong></div><div><small>TENTATIVAS</small><strong>{String(enigma.attempts).padStart(2,'0')}</strong></div><div><small>DIFICULDADE</small><strong>{enigma.difficulty.toUpperCase()}</strong></div></div>
 {loadState==='loading'?<div className={styles.unavailable} role="status"><strong>CARREGANDO CONTEÚDO DO ENIGMA...</strong></div>:!content?<div className={styles.unavailable} role="alert"><strong>CONTEÚDO DO ENIGMA INDISPONÍVEL</strong><p>Não foi possível carregar a pergunta deste enigma. Tente novamente.</p></div>:<><div className={styles.section}><small>BRIEFING</small><p>{content.briefing}</p></div><div className={`${styles.section} ${styles.mission}`}><small>OBJETIVO // MISSION OBJECTIVE</small><p>{content.objective}</p></div><div className={`${styles.section} ${styles.query}`}><small>PERGUNTA // PRIMARY QUERY</small><p>{content.question}</p></div><div className={styles.section}><small>EVIDÊNCIAS</small><div className={styles.evidence}>{evidence.map((item,index)=><button key={item.id} disabled={!item.initiallyAvailable} title={item.contentRef}><b>{String(index+1).padStart(2,'0')}</b><span>{item.title}</span></button>)}</div></div><div className={styles.hint}><div><small>PISTAS // PROGRESSIVAS</small><button onClick={()=>void requestHint()} disabled={!playable||hintBusy||allHints}>{allHints?'TODAS LIBERADAS':hintBusy?'SOLICITANDO...':'SOLICITAR PISTA'}</button></div>{Array.from({length:content.hintCount},(_,index)=>{const number=index+1,text=revealedHints[number];return <p key={number}>PISTA {String(number).padStart(2,'0')} // {text??'CLASSIFIED'}</p>})}{hintMessage&&<strong>{hintMessage}</strong>}</div></>}
 <label><span>RESPOSTA // NÃO SERÁ ARMAZENADA</span><input value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')void validate()}} placeholder={playable?'INSIRA A CHAVE...':'CONTEÚDO INDISPONÍVEL'} autoComplete="off" disabled={!playable}/></label><button className={styles.validate} onClick={()=>void validate()} disabled={!playable||!answer.trim()||busy}>{busy?'VALIDATING...':'VALIDAR RESPOSTA'} <Icon name="arrow" size={14}/></button>{result&&<div className={`${styles.result} ${result.correct?styles.success:styles.denied}`}><strong>{result.correct?'VALIDAÇÃO CONFIRMADA':result.feedbackCode==='VALIDATOR_UNAVAILABLE'?'CANAL DE VALIDAÇÃO INDISPONÍVEL':'VALIDAÇÃO NEGADA'}</strong><p>{result.correct?'PATTERN CONFIRMED. DECRYPTING... FRAGMENT RESTORED.':result.feedbackCode==='VALIDATOR_UNAVAILABLE'?'A conexão com o validador canônico não pôde ser estabelecida. Nenhuma tentativa foi perdida.':'O padrão informado não corresponde aos fragmentos recuperados.'}</p></div>}{import.meta.env.DEV&&onDevAction&&<div className={styles.dev}><small>DEV ENIGMA PANEL</small>{(['unlock','lock','solve','reset','attempt','hint']as DevAction[]).map(action=><button key={action} onClick={()=>onDevAction(action)}>{action}</button>)}</div>}</section></div>
}
