import type{EnigmaEvidence}from'../../../types'
import{narrativeApiEndpoint as endpoint,trustedApiEndpoint}from'../../../config/apiEndpoints'
export interface CanonicalHintMetadata{index:number;label:string;available:false}
export interface RevealedCanonicalHint{index:number;label:string;text:string}
export interface CanonicalEnigmaPublicContent{id:string;title:string;codename?:string;category:string;difficulty:string;briefing:string;objective:string;question:string;evidence:EnigmaEvidence[];hintCount:number;hints?:CanonicalHintMetadata[];prerequisites?:string[];unlocks?:string[]}
export type CanonicalEnigmaContent=CanonicalEnigmaPublicContent
const forbiddenKeys=new Set(['answer','acceptedanswers','canonicalanswer','aliases','alternatives','solution','secrettrigger','secrettriggers','triggers','secrets','validator','validatorlogic'])
const nonEmpty=(value:unknown):value is string=>typeof value==='string'&&value.trim().length>0
export function canonicalNarrativeConfigured(){return trustedApiEndpoint(endpoint)}
export function parseCanonicalEnigmaPublicContent(value:unknown,expectedId:string):CanonicalEnigmaPublicContent|null{if(!value||typeof value!=='object'||Array.isArray(value))return null;const record=value as Record<string,unknown>;if(Object.keys(record).some(key=>forbiddenKeys.has(key.toLowerCase())))return null;if(record.id!==expectedId||!nonEmpty(record.title)||!nonEmpty(record.category)||!nonEmpty(record.difficulty)||!nonEmpty(record.briefing)||!nonEmpty(record.objective)||!nonEmpty(record.question)||!Array.isArray(record.evidence)||typeof record.hintCount!=='number'||record.hintCount<0)return null;if(record.hints!==undefined&&!Array.isArray(record.hints))return null;return record as unknown as CanonicalEnigmaPublicContent}
export function parseRevealedCanonicalHint(value:unknown,expectedIndex:number):RevealedCanonicalHint|null{if(!value||typeof value!=='object'||Array.isArray(value))return null;const record=value as Record<string,unknown>;if(Object.keys(record).some(key=>forbiddenKeys.has(key.toLowerCase())))return null;return record.index===expectedIndex&&nonEmpty(record.label)&&nonEmpty(record.text)?record as unknown as RevealedCanonicalHint:null}
export async function loadCanonicalEnigmaContent(enigmaId:string,signal?:AbortSignal):Promise<CanonicalEnigmaContent|null>{if(!canonicalNarrativeConfigured())return null;try{const response=await fetch(`${endpoint}/v1/enigmas/${encodeURIComponent(enigmaId)}/content`,{headers:{Accept:'application/json'},signal});return response.ok?parseCanonicalEnigmaPublicContent(await response.json(),enigmaId):null}catch{return null}}
export async function revealCanonicalHint(enigmaId:string,hintIndex:number,signal?:AbortSignal):Promise<RevealedCanonicalHint|null>{if(!canonicalNarrativeConfigured()||!Number.isInteger(hintIndex)||hintIndex<1)return null;try{const response=await fetch(`${endpoint}/v1/enigmas/${encodeURIComponent(enigmaId)}/hints/reveal`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({hintIndex}),signal});return response.ok?parseRevealedCanonicalHint(await response.json(),hintIndex):null}catch{return null}}
export async function validateCanonicalAnswer(enigmaId:string,answer:string,context:{founderId:number;founderTotal:number}):Promise<'CORRECT'|'INCORRECT'|'PARTIAL'|'INVALID_FORMAT'|'VALIDATOR_UNAVAILABLE'>{if(!canonicalNarrativeConfigured())return'VALIDATOR_UNAVAILABLE';try{const response=await fetch(`${endpoint}/v1/enigmas/validate`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({enigmaId,answer,licenseContext:context})});if(!response.ok)return response.status===422?'INVALID_FORMAT':'VALIDATOR_UNAVAILABLE';const value=await response.json()as{feedbackCode?:string};return['CORRECT','INCORRECT','PARTIAL','INVALID_FORMAT'].includes(value.feedbackCode??'')?value.feedbackCode as'CORRECT'|'INCORRECT'|'PARTIAL'|'INVALID_FORMAT':'VALIDATOR_UNAVAILABLE'}catch{return'VALIDATOR_UNAVAILABLE'}}
export async function validateSecretInput(rawInput:string,context:{founderId:number;founderTotal:number}):Promise<{discovered:boolean;id?:string;message?:string}>{if(!canonicalNarrativeConfigured())return{discovered:false};try{const response=await fetch(`${endpoint}/v1/secrets/validate`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({input:rawInput,licenseContext:context})});if(!response.ok)return{discovered:false};const value=await response.json()as{discovered?:boolean;id?:string;message?:string};return{discovered:Boolean(value.discovered),id:value.id,message:value.message}}catch{return{discovered:false}}}
