import{load,type Store}from'@tauri-apps/plugin-store';import type{Investigation}from'../types/investigation'
const FILE='orpheus-investigations.json',KEY='investigations',WEB_KEY='orpheus.investigations.v1',LIMIT=10
export interface InvestigationStorage{load():Promise<Investigation[]>;save(item:Investigation):Promise<void>;delete(id:string):Promise<void>}
export const shouldPersistInvestigation=(item:Pick<Investigation,'privateMode'>)=>!item.privateMode
interface StorageLike{getItem(key:string):string|null;setItem(key:string,value:string):void}
const valid=(value:unknown):Investigation[]=>Array.isArray(value)?value.filter((item):item is Investigation=>Boolean(item&&typeof item==='object'&&(item as Investigation).version===1)).slice(0,LIMIT):[]
export class WebInvestigationStorage implements InvestigationStorage{constructor(private storage:StorageLike=localStorage){}async load(){try{return valid(JSON.parse(this.storage.getItem(WEB_KEY)??'[]'))}catch{return[]}}async save(item:Investigation){const all=(await this.load()).filter(entry=>entry.id!==item.id);this.storage.setItem(WEB_KEY,JSON.stringify([item,...all].slice(0,LIMIT)))}async delete(id:string){this.storage.setItem(WEB_KEY,JSON.stringify((await this.load()).filter(item=>item.id!==id)))}}
class TauriInvestigationStorage implements InvestigationStorage{private promise:Promise<Store>|null=null;private store(){return this.promise??=load(FILE,{autoSave:false,defaults:{}})}async load(){return valid(await(await this.store()).get(KEY))}async save(item:Investigation){const store=await this.store();const all=(await this.load()).filter(entry=>entry.id!==item.id);await store.set(KEY,[item,...all].slice(0,LIMIT));await store.save()}async delete(id:string){const store=await this.store();await store.set(KEY,(await this.load()).filter(item=>item.id!==id));await store.save()}}
export const createInvestigationStorage=():InvestigationStorage=>'__TAURI_INTERNALS__'in window?new TauriInvestigationStorage():new WebInvestigationStorage()
